version: "3.3"

volumes:
  npm_cache:

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev

    command: [sh, /app/install_and_run.sh]
    
    tty: true
    
    environment:
      NPM_CONFIG_CACHE: /var/tmp/npm_cache
      NODE_ENV: development

    volumes:
      - .:/app
      - npm_cache:/var/tmp/npm_cache

      - /app/packages/musicbot/node_modules
      - /app/packages/plugin-source-spotify/node_modules
      - /app/packages/plugin-source-youtube-dl/node_modules
      - /app/packages/plugin-teamspeak3/node_modules
      - /app/packages/plugin-webadmin/node_modules
      - /app/node_modules
